[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-arg=-sERROR_ON_UNDEFINED_SYMBOLS=0",
    "-C", "link-arg=-sEXPORTED_RUNTIME_METHODS=['ccall','cwrap']",
    "-C", "link-arg=-sEXPORTED_FUNCTIONS=['_main','_emscripten_asm_const_int']",
    "-C", "link-arg=-sALLOW_MEMORY_GROWTH=1",
    "-C", "link-arg=-sENVIRONMENT=web",
    "-C", "link-arg=-sEXPORT_ALL=1",
    "-C", "link-arg=-sEXPORT_ES6=1",
    "-C", "link-arg=-sMODULARIZE=1",
    "-C", "link-arg=-sUSE_ES6_IMPORT_META=0",
    "-C", "link-arg=-sASYNCIFY"
]